### ISSUE TITLE
Some info

### ISSUE THREAD

**Issue by Pairman** [Rrrilac/XDUsign#1]
I have been working on a similar project (you can refer to my repos page) since a year ago, it supports multiplatform and also has a automatic cli script (not released publicly). And today I happened to find your xdusign repo when solving vpProbability related issues.

Hopefully my repo can be useful for your project. And if you like, you can share your contact with me in some secure way.

**Comment by Rrrilac** [comment]
ZmFudGFzeWhhdGhAZ21haWwuY29t
base64

**Comment by Rrrilac** [comment]
Check your gmail.
